DRAFT: Improve documentation across the entire project
libmir/mir-ion pull request #207
Opened 2021-10-18 18:25 UTC by hatf0

2021-11-01 16:18 UTC, hatf0 commented
I'm thinking of extracting out the massive collection of examples out to the `examples/` folder, just because I believe they're currently a little hard to follow. 

Also, @9il, what does the `annotated` flag do (w.r.t. `deserializeIon`)?

2021-11-02 09:34 UTC, 9il commented
> Also, @9il, what does the `annotated` flag do (w.r.t. `deserializeIon`)?

It is adds addtional `IonAnnotatoins` argument. The problem is that we may wan't to handle the first one annotation while the following one annotations are related to the value itself. So, this flags helps to solve annotation encapsulation.

2021-11-06 05:47 UTC, 9il commented
- The pivot table of UDAs, even with empty descriptions
- binary literals
- CLOB and BLOB support (do we already support CLOBs?)

have priority over examples

2021-11-06 05:48 UTC, 9il requested changes

2021-11-06 05:48 UTC, 9il commented on examples/basic-attributes/source/app.d
> +	@serdeRequired
Members are required by default. This attribute is redundant.

2021-11-06 05:48 UTC, 9il commented on examples/basic-attributes/source/app.d
> +		static immutable data = q"{
It is better to use `` or q{}. q"" doesn't look nice.

2021-11-06 05:48 UTC, 9il commented on examples/basic-attributes/source/app.d
> +			}
One line definition looks better better.

2021-11-06 05:48 UTC, 9il commented on examples/basic-attributes/source/app.d
> +	// For the sake of clarity, all examples below will be in the Ion text format. However,
Please use 4 spaces, not tabs

2021-11-06 05:48 UTC, 9il commented on examples/basic-attributes/source/app.d
> +import mir.serde;
Selective imports are desired for examples, it makes clear where the definition can be found.

2021-11-06 18:13 UTC, hatf0 commented
> * The pivot table of UDAs, even with empty descriptions
> * binary literals
> * CLOB and BLOB support (do we already support CLOBs?)
> 
> have priority over examples

Understood, I’ll focus on those then. We also already support clobs, it’s just blob support that’s missing (due to no base64 decoding support in Mir Algorithm).

2021-11-07 05:04 UTC, 9il commented
> due to no base64 decoding support in Mir Algorithm

Please add it

2021-12-05 13:39 UTC, closed without merging