Refactor msgpack backend to remove msgpack-d dependency
libmir/mir-ion pull request #4
Opened 2022-02-04 18:43 UTC by hatf0

WIP. See issue #2 for more information.

2022-02-05 12:25 UTC, 9il commented on source/mir/ion/ser/msgpack.d
> +            else if ((num & 0b1111_1111_1111_1111_1111_1111_0000_0000_0000_0000_0000_0000_0000_0000) == 0)
Please use hexadecimal literals.

2022-02-09 00:56 UTC, hatf0 commented
Do not merge yet -- I have to refactor some bits and pull out the usage of ScopedBuffer (as it's now going out of scope and causing a use after free)

2022-02-09 05:03 UTC, 9il commented
Please add extra 4 spaces  for the whole MsgpackSerializer. And use the same order of methods like in the original code. That is needed to reduce the diff for easier review.

2022-02-09 05:05 UTC, 9il commented
We need 100% coverage of the new code for the message pack. It is a critical part of code used in production.

2022-02-09 17:50 UTC, hatf0 commented
> We need 100% coverage of the new code for the message pack. It is a critical part of code used in production.

I was able to get coverage up to 98% on this file, if that's fine. The only code that isn't covered is:
https://github.com/libmir/mir-ion/blob/f143764fc10701beda287f72cc38eec0042f5b8a/source/mir/ion/ser/msgpack.d#L572-L575
https://github.com/libmir/mir-ion/blob/f143764fc10701beda287f72cc38eec0042f5b8a/source/mir/ion/ser/msgpack.d#L537-L540
Both of these aren't feasible to test (as they'd require that we allocate a `const(char)[]` array that is 4.29 GB in size)
https://github.com/libmir/mir-ion/blob/f143764fc10701beda287f72cc38eec0042f5b8a/source/mir/ion/ser/msgpack.d#L317-L318
and I'm not sure how to trigger this code path.

2022-02-10 07:06 UTC, 9il commented
> @9il, I was able to get coverage up to 98% on this file, if that's fine. The only code that isn't covered is:

That is enough, thank you

2022-02-10 07:40 UTC, 9il requested changes
A few nitpicks. Overall looks good.

2022-02-10 07:40 UTC, 9il commented on source/mir/ion/ser/msgpack.d
> +            if ((num & 0xffffff00) == 0)
That step isn't needed. The ushort handler will cate about ubyte case anyway.

2022-02-10 07:40 UTC, 9il commented on source/mir/ion/ser/msgpack.d
> +            if ((num & 0xffffffffffffff00) == 0)
ditto

2022-02-10 07:40 UTC, 9il commented on source/mir/ion/ser/msgpack.d
> +            if ((num & 0xffffffffffff0000) == 0)
ditto

2022-02-10 07:40 UTC, 9il commented on source/mir/ion/ser/msgpack.d
> +            if (num & 0x80)
`num < 0` looks better

2022-02-10 07:40 UTC, 9il commented on source/mir/ion/ser/msgpack.d
> +            if (num >= byte.min && num <= byte.max)
`num == cast(byte) num` is faster path and simplier to get

2022-02-10 07:40 UTC, 9il commented on source/mir/ion/ser/msgpack.d
> +            if (num >= short.min && num <= short.max)
ditto

2022-02-10 07:40 UTC, 9il commented on source/mir/ion/ser/msgpack.d
> +            if (num >= int.min && num <= int.max)
ditto

2022-02-10 07:40 UTC, 9il commented on source/mir/ion/ser/msgpack.d
> +        void putValue(const ubyte num)
All non template method shouldn't mark arguments as head const: just `ubyte num` is better

2022-02-10 07:40 UTC, 9il commented on source/mir/ion/ser/msgpack.d
> +            uint v = *cast(uint*)&num;
OK, but wrap it into a trusted lambda.

2022-02-10 07:40 UTC, 9il commented on source/mir/ion/ser/msgpack.d
> +            ulong v = *cast(ulong*)&num;
ditto

2022-02-10 07:40 UTC, 9il commented on source/mir/ion/ser/msgpack.d
> +            buffer.put(cast(ubyte)(0xc2 | b));
`cast(ubyte)(MessagePackFmt.false_ | b)`

2022-02-10 07:40 UTC, 9il commented on source/mir/ion/ser/msgpack.d
> +    timestamp32 = 0xd6,
`fixext4` should be used instead

2022-02-10 07:40 UTC, 9il commented on source/mir/ion/ser/msgpack.d
> +    timestamp64 = 0xd7,
`fixext8` should be used instead

2022-02-10 07:40 UTC, 9il commented on source/mir/ion/ser/msgpack.d
> +    timestamp96 = 0xc7,
`ext8` should be used instead

2022-02-10 07:40 UTC, 9il commented on source/mir/ion/ser/msgpack.d
> +import mir.serde: SerdeTarget;
move it into the file start

2022-02-10 07:40 UTC, 9il commented on source/mir/ion/ser/msgpack.d
> +version(mir_ion_test) unittest
All test below should be `@safe pure`

2022-02-10 17:55 UTC, rv32ima commented
Alright. I've added your requested fixes -- let me know if there's anything else that need fixing.

2022-02-11 12:51 UTC, merged

2022-02-11 12:51 UTC, 9il commented
Looks good.